### ISSUE TITLE
Custom Describer fails

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#4023]
I'm getting an error from boards which use references:

```javascript
Error while invoking graph's custom describer Error: Error loading module: Error: Error resolving module '@output' from 'output'

    at __wbindgen_error_new (factory.js:356:13)
    at sandbox.wasm:0xdeab7
    at sandbox.wasm:0xbb09e
    at sandbox.wasm:0x1cd92
    at sandbox.wasm:0xa7732
    at sandbox.wasm:0xde3bf
    at sandbox.wasm:0xdecb1
    at __wbg_adapter_24 (factory.js:199:6)
    at real (factory.js:184:8)
```

It's happening in `#tryDescribingWithCustomDescriber` at `describer-manager.ts:420`

**Comment by dglazkov** [comment]
Interesting! It sounds like that build doesn't yet have the output capability. What can I do to reproduce?

**Comment by paullewis** [comment]
Looks like Vite may have cached things! Seems to be working now.
