### ISSUE TITLE
`Board.load` should not require `option.base` when an absolute path is passed

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#494]
discovered when @TinaNikou was updated for `0.8.0` 

error:
```
node_modules/@google-labs/breadboard/dist/src/loader.js:11
    const baseWithoutHash = base.href.replace(base.hash, "");
                                 ^
TypeError: Cannot read properties of undefined (reading 'href')
    at resolveURL (node_modules/@google-labs/breadboard/dist/src/loader.js:11:34)
    at BoardLoader.load (node_modules/@google-labs/breadboard/dist/src/loader.js:81:17)
    at Function.load (node_modules/@google-labs/breadboard/src/runner.ts:367:48)
    at <anonymous> (src/board.ts:42:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

see: https://discord.com/channels/1138546999872999556/1138554749537484810/1200435711439032471

**Comment by dglazkov** [comment]
so... what if we, instead of this whole `base` and `url` dance just made `url` a `URL` type?

**Comment by Mearman** [comment]
seems sensible to me

**Comment by PaulKinlan** [comment]
Big +1 to this.
