### ISSUE TITLE
Editor: Trying to delete all nodes causes an error

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#845]
If I go into the editor and try to remove the input & output I get the following:

```
node.ts:165 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'values')
    at InspectableNodeCache.nodes (node.ts:165:44)
    at Graph.nodes (graph.ts:118:24)
    at #processGraph (editor.ts:303:40)
    at Editor.updated (editor.ts:420:25)
    at Editor._$didUpdate (chunk-D3ZHFRMU.js?v=2d610eb4:780:10)
    at Editor.performUpdate (chunk-D3ZHFRMU.js?v=2d610eb4:742:12)
    at Editor.scheduleUpdate (chunk-D3ZHFRMU.js?v=2d610eb4:676:25)
    at Editor.__enqueueUpdate (chunk-D3ZHFRMU.js?v=2d610eb4:652:25)
```

**Comment by paullewis** [comment]
Have landed a workaround

**Comment by dglazkov** [comment]
Excellent catch. I got too clever with the shortcuts!

**Comment by dglazkov** [comment]
Added test!
